<!-- import torch
print(torch.__version__)  -->


In [ ]:
import torch
print(torch.__version__) 

In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using gpu : {torch.cuda.get_device_name(0)}")
elif hasattr(torch,'mps') and torch.backends.mps.is_available():
    print("MPS is available")
else:
    print("Neither GPU nor MPS is available")


MPS is available


# Creating a Tensor

In [4]:
t1 = torch.empty(2,3)
# empty function allocate memory of (2,3) , not assigned values just show already there value.
print(t1)
print(type(t1))

t2 = torch.zeros(2,3)
# create a tensor of (2,3) with zeros
print(t2)
print(type(t2))

t3 = torch.ones(2,3)
# create a tensor of (2,3) with ones
print(t3)
print(type(t3))


t4 = torch.rand(2,3)
# create a tensor of (2,3) with random values
# note when it run again , it gives diff value
print(t4)
print(type(t4))


tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0.5755, 0.5333, 0.5717],
        [0.5460, 0.7536, 0.3926]])
<class 'torch.Tensor'>


In [5]:
torch.manual_seed(100)
t4 = torch.rand(2,3)

print(t4)

# Since , torch.rand give diff value on always run , so we use manual seed , which 
# If you remove manual_seed, the numbers will change each run.
# torch.manual_seed(n) Fix randomness for CPU & GPU ops (except some CUDA)
# Improves reproducibility : Yes
# Required for training : No, but recommended for consistent results

torch.manual_seed(100)
t5 = torch.rand(2,3)

print(t5)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [6]:
t6 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(t6)
print(t6.shape)
print(type(t6))

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
<class 'torch.Tensor'>


In [7]:
print("using arange")
print(torch.arange(0,10,2))  # the range (0 to 10) with step of 2


print("Using linspace")
print(torch.linspace(0,10,10))  # give me 10 evenly placed values from range 0 to 10


print("Using eye")
print(torch.eye(5))  # here eye is for identity matrix


print("Using full")
print(torch.full((3,3),5))   # you are filling tensor of shape (3,3) with 5


print("Using full")
print(torch.full((2,3,3),5))   # you are filling tensor of shape (3,3) with 5

using arange
tensor([0, 2, 4, 6, 8])
Using linspace
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
Using full
tensor([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]])


In [8]:
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(t1)
print(t1.shape)

t2 = torch.empty_like(t1)   # same shape but value can differ
print(t2)
print(t2.shape)

t3 = torch.ones_like(t1)   # same shape but value 1 
print(t3)
print(t3.shape)

# slly for zeros use zeros_like

t4 = torch.rand_like(t1 , dtype=torch.float64)   # you shoudl specify dtype of value in rand_like
print(t4)
print(t4.shape)

# slly for zeros use zeros_like

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[0, 0, 0],
        [0, 0, 0]])
torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]])
torch.Size([2, 3])
tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)
torch.Size([2, 3])


# Tensor DataType

In [9]:
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.int32
)

print(t1)
print(type(t1))
print(t1.dtype)

t2 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.float64
)

print(t2)
print(type(t2))
print(t2.dtype)


t3 = t1.to(torch.float32) # change the dtype of existing
print(t3)
print(t3.dtype)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


# 1. Mathematical Scalar Operations

In [10]:
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.int32
)

print(t1)


# Scaler Operations

print("Addition")
print(t1 + 2)

print("Subtraction")
print(t1 - 2)

print("Multiplication")
print(t1 * 2)

print("Division")
print(t1 / 2)

print("Int Division")
print(t1 // 2)

print("Mod")
print( (t1 // 2) % 2)

print("Power")
print( t1**2 )

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)

print(b)

print("Addition")
print(a + b)

print("Subtraction")
print(a - b)

print("Multiplication")
print(a * b)

print("Division")
print(a/b)

print("Power")
print( a ** b)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Addition
tensor([[3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)
Subtraction
tensor([[-1,  0,  1],
        [ 2,  3,  4]], dtype=torch.int32)
Multiplication
tensor([[ 2,  4,  6],
        [ 8, 10, 12]], dtype=torch.int32)
Division
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
Int Division
tensor([[0, 1, 1],
        [2, 2, 3]], dtype=torch.int32)
Mod
tensor([[0, 1, 1],
        [0, 0, 1]], dtype=torch.int32)
Power
tensor([[ 1,  4,  9],
        [16, 25, 36]], dtype=torch.int32)
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
Addition
tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])
Subtraction
tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])
Multiplication
tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])
Division
tensor([[0.5042, 0.3190, 0.2397],
        [

# 2. Math Functions

In [11]:
x = torch.tensor(
    [1.9,2.3,3,-4]
)

print(x)

print("Absolute" , torch.abs(x))

print("Negative" , torch.neg(x))

print("Round" , torch.round(x))

print("Ceil" , torch.ceil(x))

print("Floor" , torch.floor(x))

print("Clamp" , torch.clamp(x , min = 2,max = 4)) # set numbers in range like < 2 : 2 , > 4 : 4

tensor([ 1.9000,  2.3000,  3.0000, -4.0000])
Absolute tensor([1.9000, 2.3000, 3.0000, 4.0000])
Negative tensor([-1.9000, -2.3000, -3.0000,  4.0000])
Round tensor([ 2.,  2.,  3., -4.])
Ceil tensor([ 2.,  3.,  3., -4.])
Floor tensor([ 1.,  2.,  3., -4.])
Clamp tensor([2.0000, 2.3000, 3.0000, 2.0000])


# 3. Reduce Operation

In [12]:
t1 = torch.randint(
    size = (2,3),
    low = 0 ,
    high = 10,
    dtype=torch.float64
)

print(t1)

print("Sum" , torch.sum(t1))
print("Sum along columns" , torch.sum(t1 , dim = 0))
print("Sum along rows" , torch.sum(t1 , dim = 1))

print("Mean" , torch.mean(t1))
print("Mean along columns" , torch.mean(t1 , dim = 0))
print("Mean along rows" , torch.mean(t1 , dim = 1))
# mean required dtype to be float
# slly median

print("Max" , torch.max(t1))
print("Max along columns" , torch.max(t1 , dim = 0))
print("Max along rows" , torch.max(t1 , dim = 1))

print("Product" , torch.prod(t1))
print("Product along columns" , torch.prod(t1 , dim = 0))
print("Product along rows" , torch.prod(t1 , dim = 1))


tensor([[7., 0., 0.],
        [9., 5., 7.]], dtype=torch.float64)
Sum tensor(28., dtype=torch.float64)
Sum along columns tensor([16.,  5.,  7.], dtype=torch.float64)
Sum along rows tensor([ 7., 21.], dtype=torch.float64)
Mean tensor(4.6667, dtype=torch.float64)
Mean along columns tensor([8.0000, 2.5000, 3.5000], dtype=torch.float64)
Mean along rows tensor([2.3333, 7.0000], dtype=torch.float64)
Max tensor(9., dtype=torch.float64)
Max along columns torch.return_types.max(
values=tensor([9., 5., 7.], dtype=torch.float64),
indices=tensor([1, 1, 1]))
Max along rows torch.return_types.max(
values=tensor([7., 9.], dtype=torch.float64),
indices=tensor([0, 0]))
Product tensor(0., dtype=torch.float64)
Product along columns tensor([63.,  0.,  0.], dtype=torch.float64)
Product along rows tensor([  0., 315.], dtype=torch.float64)


In [13]:
print("Standard Deviation" , torch.std(t1))
print("Variance" , torch.var(t1))
print("Argmax" , torch.argmax(t1)) # return index
print("Argmin" , torch.argmin(t1)) 

Standard Deviation tensor(3.8297, dtype=torch.float64)
Variance tensor(14.6667, dtype=torch.float64)
Argmax tensor(3)
Argmin tensor(1)


# 4. Matrix Operations

In [14]:
t1 = torch.randint(
    size = (2,3),
    low = 0 ,
    high = 10,
    dtype=torch.float64
)

t2 = torch.randint(
    size = (3,2),
    low = 0 ,
    high = 10,
    dtype=torch.float64
)


print("Matrix multiplication")
t3 = torch.matmul(t1,t2)
print(t3)

print("Transpose")
t4 = torch.transpose(t1 , 0 , 1)  # i.e swapping dim 0 with 1 
print(t4)

# For a 3D tensor shaped (batch, channels, height):
# tensor.transpose(1, 2)  # swap channels and height



Matrix multiplication
tensor([[116., 126.],
        [ 80.,  98.]], dtype=torch.float64)
Transpose
tensor([[3., 0.],
        [9., 5.],
        [4., 7.]], dtype=torch.float64)


In [15]:
# dot pdt done on 1d tensors
vector1 = torch.tensor([0.1,0.2,0.3])
vector2 = torch.rand_like(vector1)
# rand generate no between 0 and 1

print(vector1)
print(vector2)

print("Dot Product")
vector3 = torch.dot(vector1,vector2)
print(vector3)

tensor([0.1000, 0.2000, 0.3000])
tensor([0.9051, 0.5989, 0.4450])
Dot Product
tensor(0.3438)


In [16]:
t1 = torch.randint(
    size = (3,3),
    low = 0 ,
    high = 10,
    dtype=torch.float64
)

print(t1)


print("Determinant") 
t2 = torch.det(t1)  # for square matrix
print(t2)

print("Inverse") 
t3 = torch.inverse(t1)  # for square matrix
print(t3)


tensor([[9., 2., 6.],
        [7., 7., 8.],
        [3., 6., 1.]], dtype=torch.float64)
Determinant
tensor(-209., dtype=torch.float64)
Inverse
tensor([[ 0.1962, -0.1627,  0.1244],
        [-0.0813,  0.0431,  0.1435],
        [-0.1005,  0.2297, -0.2344]], dtype=torch.float64)


In [17]:
t1 = torch.randint(
    size = (3,3),
    low = 0 ,
    high = 10,
    dtype=torch.float64
)

t2 = torch.randint(
    size = (3,3),
    low = 0 ,
    high = 10,
    dtype=torch.float64
)

print("Comparision Operations")
print(t1 > t2)

# slly = , <= , >= etc.

Comparision Operations
tensor([[False,  True, False],
        [False,  True, False],
        [ True, False,  True]])


# 5. Special Functions

In [18]:
a = torch.randint( size = (2 , 3) , low = 0 , high = 10 ,  dtype=torch.float64 ) 

print(a)

print("Log")
print(torch.log(a))

print("Exponent")
print(torch.exp(a))

print("Sqrt")
print(torch.sqrt(a))


print("Sigmoid")
print(torch.sigmoid(a))

print("Softmax")
print(torch.softmax(a , dim = 0)) # along column 

print("Relu")
print(torch.relu(a)) 




tensor([[3., 8., 5.],
        [6., 2., 9.]], dtype=torch.float64)
Log
tensor([[1.0986, 2.0794, 1.6094],
        [1.7918, 0.6931, 2.1972]], dtype=torch.float64)
Exponent
tensor([[2.0086e+01, 2.9810e+03, 1.4841e+02],
        [4.0343e+02, 7.3891e+00, 8.1031e+03]], dtype=torch.float64)
Sqrt
tensor([[1.7321, 2.8284, 2.2361],
        [2.4495, 1.4142, 3.0000]], dtype=torch.float64)
Sigmoid
tensor([[0.9526, 0.9997, 0.9933],
        [0.9975, 0.8808, 0.9999]], dtype=torch.float64)
Softmax
tensor([[0.0474, 0.9975, 0.0180],
        [0.9526, 0.0025, 0.9820]], dtype=torch.float64)
Relu
tensor([[3., 8., 5.],
        [6., 2., 9.]], dtype=torch.float64)


# 6. Inplace operations

In [19]:
a = torch.randint( size = (2 , 3) , low = 0 , high = 10 ,  dtype=torch.float64 ) 

print(torch.relu(a)) 
print("Inplace" , a.relu_())
# slly inplace functions cna be like add_ etc.

tensor([[5., 0., 4.],
        [2., 7., 1.]], dtype=torch.float64)
Inplace tensor([[5., 0., 4.],
        [2., 7., 1.]], dtype=torch.float64)


# 7. Copying a tensor

In [20]:
a = torch.rand(2,3)
print(a)

b = a

a[0][0] = 0
print(a)
print(b)


print(id(a)) # memory location of a
print(id(b)) # memory location of b


tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])
tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])
tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])
5126513328
5126513328


In [21]:
a = torch.rand(2,3)
print(a)

b = a.clone()


a[0][0] = 0
print(a)
print(b)

print(id(a)) # memory location of a
print(id(b)) # memory location of b



tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])
tensor([[0.0000, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])
tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])
5126512448
5126514928


# Tensor Operations on GPU 

In [22]:
device = torch.device('cpu')
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")
    print(f"Using gpu : {torch.cuda.get_device_name(0)}")
elif hasattr(torch,'mps') and torch.backends.mps.is_available():
    device = torch.device("mps")
    print("MPS is available")
else:
    print("Neither GPU nor MPS is available")

MPS is available


In [23]:
print(device)

mps


In [24]:
t1 = torch.rand( (2,3) , device = device )
print(t1)

tensor([[0.4643, 0.8532, 0.4872],
        [0.4602, 0.4261, 0.0968]], device='mps:0')


In [25]:
# Move existing tensor to gpu 
t1 = torch.rand(2,3)
print(t1)

t2 = t1.to(device)
print(t2)

# there is no copying , it is like cloning , diff memory

t1[0][0] = 0
print(t2)

print(id(t1))
print(id(t2))

tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]])
tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]], device='mps:0')
tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]], device='mps:0')
5126517408
5126517888


# Comparing Speed

In [26]:
import time 

size = 1000

print("CPU")

t1_cpu = torch.rand(size , size)
t2_cpu = torch.rand(size , size)

start_time = time.time()
result_cpu = torch.matmul(t1_cpu , t2_cpu)
time_cpu = time.time() - start_time

print(time_cpu)


print("GPU")

t1_gpu = t1_cpu.to(device)
t2_gpu = t2_cpu.to(device)

start_time = time.time()
result_gpu = torch.matmul(t1_gpu , t2_gpu)

time_gpu = time.time() - start_time

print(time_gpu)


print(f"GPU is {time_cpu/time_gpu}faster than CPU")


CPU
0.002167940139770508
GPU
0.004545927047729492
GPU is 0.4768972570409608faster than CPU


# Reshaping Tensors

In [27]:
t1 = torch.rand(4,2,3)
print(t1.shape)
print(t1)

print("Reshaping")
print(t1.reshape(2,2,6))
# product of shape initial must equal to final

print("Flatten")
print(t1.flatten())

torch.Size([4, 2, 3])
tensor([[[0.1562, 0.8485, 0.4441],
         [0.5472, 0.0124, 0.0467]],

        [[0.2321, 0.9232, 0.6272],
         [0.9363, 0.7697, 0.9526]],

        [[0.6208, 0.0330, 0.6702],
         [0.2086, 0.7164, 0.1627]],

        [[0.5908, 0.2001, 0.7692],
         [0.3234, 0.5739, 0.9485]]])
Reshaping
tensor([[[0.1562, 0.8485, 0.4441, 0.5472, 0.0124, 0.0467],
         [0.2321, 0.9232, 0.6272, 0.9363, 0.7697, 0.9526]],

        [[0.6208, 0.0330, 0.6702, 0.2086, 0.7164, 0.1627],
         [0.5908, 0.2001, 0.7692, 0.3234, 0.5739, 0.9485]]])
Flatten
tensor([0.1562, 0.8485, 0.4441, 0.5472, 0.0124, 0.0467, 0.2321, 0.9232, 0.6272,
        0.9363, 0.7697, 0.9526, 0.6208, 0.0330, 0.6702, 0.2086, 0.7164, 0.1627,
        0.5908, 0.2001, 0.7692, 0.3234, 0.5739, 0.9485])


In [28]:
t1 = torch.rand(4,2,3)
print(t1.shape)

print("Permute")
print(t1.permute(2,0,1).shape)   # replace 0 : 2 , 1 : 0 , 2 : 1
print(t1.permute(2,0,1)) 

torch.Size([4, 2, 3])
Permute
torch.Size([3, 4, 2])
tensor([[[0.2220, 0.1317],
         [0.1248, 0.6519],
         [0.2712, 0.1564],
         [0.5599, 0.1843]],

        [[0.2173, 0.1610],
         [0.7583, 0.4037],
         [0.4102, 0.9509],
         [0.9476, 0.3103]],

        [[0.3704, 0.9557],
         [0.6898, 0.8527],
         [0.3974, 0.1346],
         [0.5768, 0.2648]]])


In [29]:
t1 = torch.rand(226,226,3)
print(t1.shape)

print("Unsqueeze")
# adding dimension at a given position
# eg to be used for batch

print(t1.unsqueeze(0).shape)
print(t1.unsqueeze(1).shape)
print(t1.unsqueeze(2).shape)

torch.Size([226, 226, 3])
Unsqueeze
torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])
torch.Size([226, 226, 1, 3])


In [30]:
t1 = torch.rand(1,4,1,226,3)
print(t1.shape)

print("Squeeze")
# remove dimension at a given position (only 1)

print(t1.squeeze(0).shape)  # (4,1,226,3)
print(t1.squeeze(1).shape)  # (1,4,1,226,3)
print(t1.squeeze(2).shape)  # (1,4,226,3)

torch.Size([1, 4, 1, 226, 3])
Squeeze
torch.Size([4, 1, 226, 3])
torch.Size([1, 4, 1, 226, 3])
torch.Size([1, 4, 226, 3])


# Numpy and Pytorch

In [31]:
import numpy

a = torch.tensor([1,2,3])

print(type(a))
print(a)

b = a.numpy()

print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([1, 2, 3])
<class 'numpy.ndarray'>
[1 2 3]


In [32]:
a = numpy.array([1,2,3])

print(type(a))
print(a)

b = torch.from_numpy(a)

print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3]
<class 'torch.Tensor'>
tensor([1, 2, 3])


| Function                        | What it does                                                      | Copy vs Share memory |
| ------------------------------- | ----------------------------------------------------------------- | -------------------- |
| `torch.tensor(numpy_array)`     | Creates a **new tensor copy** from NumPy data                     | Copy (new memory)  |
| `torch.from_numpy(numpy_array)` | Creates a tensor that **shares the same memory** with NumPy array | Shares memory      |


In [4]:
import numpy as np
import torch

x = np.arange(8)
t = torch.from_numpy(x).reshape(2, 4)

print(type(x)  , x.shape , x)  # (8,)
print(type(t)  , t.shape , t)  # (2, 4)

# They share data (values in memory)
# But they do not share shape
# And they do not become the same type

t[0][0] = 5

print(x)
print(t)


<class 'numpy.ndarray'> (8,) [0 1 2 3 4 5 6 7]
<class 'torch.Tensor'> torch.Size([2, 4]) tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
[5 1 2 3 4 5 6 7]
tensor([[5, 1, 2, 3],
        [4, 5, 6, 7]])
