In [15]:
import torch
print(torch.__version__) 

2.9.1


In [16]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using gpu : {torch.cuda.get_device_name(0)}")
elif hasattr(torch,'mps') and torch.backends.mps.is_available():
    print("MPS is available")
else:
    print("Neither GPU nor MPS is available")


MPS is available


Creating a Tensor

In [17]:
t1 = torch.empty(2,3)
# empty function allocate memory of (2,3) , not assigned values just show already there value.
print(t1)
print(type(t1))

t2 = torch.zeros(2,3)
# create a tensor of (2,3) with zeros
print(t2)
print(type(t2))

t3 = torch.ones(2,3)
# create a tensor of (2,3) with ones
print(t3)
print(type(t3))


t4 = torch.rand(2,3)
# create a tensor of (2,3) with random values
# note when it run again , it gives diff value
print(t4)
print(type(t4))


tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
<class 'torch.Tensor'>


In [24]:
torch.manual_seed(100)
t4 = torch.rand(2,3)

print(t4)

# Since , torch.rand give diff value on always run , so we use manual seed , which 
# If you remove manual_seed, the numbers will change each run.
# torch.manual_seed(n) Fix randomness for CPU & GPU ops (except some CUDA)
# Improves reproducibility : Yes
# Required for training : No, but recommended for consistent results

torch.manual_seed(100)
t5 = torch.rand(2,3)

print(t5)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [29]:
t6 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(t6)
print(t6.shape)
print(type(t6))

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
<class 'torch.Tensor'>


In [34]:
print("using arange")
print(torch.arange(0,10,2))  # the range (0 to 10) with step of 2


print("Using linspace")
print(torch.linspace(0,10,10))  # give me 10 evenly placed values from range 0 to 10


print("Using eye")
print(torch.eye(5))  # here eye is for identity matrix


print("Using full")
print(torch.full((3,3),5))   # you are filling tensor of shape (3,3) with 5


print("Using full")
print(torch.full((2,3,3),5))   # you are filling tensor of shape (3,3) with 5

using arange
tensor([0, 2, 4, 6, 8])
Using linspace
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
Using full
tensor([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]])


In [46]:
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(t1)
print(t1.shape)

t2 = torch.empty_like(t1)   # same shape but value can differ
print(t2)
print(t2.shape)

t3 = torch.ones_like(t1)   # same shape but value 1 
print(t3)
print(t3.shape)

# slly for zeros use zeros_like

t4 = torch.rand_like(t1 , dtype=torch.float64)   # you shoudl specify dtype of value in rand_like
print(t4)
print(t4.shape)

# slly for zeros use zeros_like

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[0, 0, 0],
        [0, 0, 0]])
torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]])
torch.Size([2, 3])
tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)
torch.Size([2, 3])


Tensor DataType

In [47]:
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.int32
)

print(t1)
print(type(t1))
print(t1.dtype)

t2 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.float64
)

print(t2)
print(type(t2))
print(t2.dtype)


t3 = t1.to(torch.float32) # change the dtype of existing
print(t3)
print(t3.dtype)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


# 1. Mathematical Scalar Operations

In [57]:
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.int32
)

print(t1)


# Scaler Operations

print("Addition")
print(t1 + 2)

print("Subtraction")
print(t1 - 2)

print("Multiplication")
print(t1 * 2)

print("Division")
print(t1 / 2)

print("Int Division")
print(t1 // 2)

print("Mod")
print( (t1 // 2) % 2)

print("Power")
print( t1**2 )

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)

print(b)

print("Addition")
print(a + b)

print("Subtraction")
print(a - b)

print("Multiplication")
print(a * b)

print("Division")
print(a/b)

print("Power")
print( a ** b)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Addition
tensor([[3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)
Subtraction
tensor([[-1,  0,  1],
        [ 2,  3,  4]], dtype=torch.int32)
Multiplication
tensor([[ 2,  4,  6],
        [ 8, 10, 12]], dtype=torch.int32)
Division
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
Int Division
tensor([[0, 1, 1],
        [2, 2, 3]], dtype=torch.int32)
Mod
tensor([[0, 1, 1],
        [0, 0, 1]], dtype=torch.int32)
Power
tensor([[ 1,  4,  9],
        [16, 25, 36]], dtype=torch.int32)
tensor([[0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])
tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])
Addition
tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])
Subtraction
tensor([[-0.2648,  0.2065, -0.1576],
        [ 0.0464, -0.4397, -0.1557]])
Multiplication
tensor([[0.6535, 0.1405, 0.0174],
        [0.8780, 0.2508, 0.0017]])
Division
tensor([[0.7217, 1.7233, 0.3218],
        [

# 2. Math Functions

In [66]:
x = torch.tensor(
    [1.9,2.3,3,-4]
)

print(x)

print("Absolute" , torch.abs(x))

print("Negative" , torch.neg(x))

print("Round" , torch.round(x))

print("Ceil" , torch.ceil(x))

print("Floor" , torch.floor(x))

print("Clamp" , torch.clamp(x , min = 2,max = 4)) # set numbers in range like < 2 : 2 , > 4 : 4

tensor([ 1.9000,  2.3000,  3.0000, -4.0000])
Absolute tensor([1.9000, 2.3000, 3.0000, 4.0000])
Negative tensor([-1.9000, -2.3000, -3.0000,  4.0000])
Round tensor([ 2.,  2.,  3., -4.])
Ceil tensor([ 2.,  3.,  3., -4.])
Floor tensor([ 1.,  2.,  3., -4.])
Clamp tensor([2.0000, 2.3000, 3.0000, 2.0000])


# 3. Reduce Operation

In [ ]:
t1 = torch.r