In [1]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
print(df.shape)
print(df.columns)
df.drop(columns=['id' ,'Unnamed: 32' ] , inplace = True)

df.head()

(569, 33)
Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [4]:
xtrain,xtest,ytrain,ytest = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [5]:
xtrain

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
462       14.400         26.99           92.25      646.1          0.06995   
146       11.800         16.58           78.99      432.0          0.10910   
445       11.990         24.89           77.61      441.3          0.10300   
234        9.567         15.91           60.21      279.6          0.08464   
516       18.310         20.58          120.80     1052.0          0.10680   
..           ...           ...             ...        ...              ...   
371       15.190         13.21           97.65      711.8          0.07963   
95        20.260         23.03          132.40     1264.0          0.09078   
440       10.970         17.20           71.73      371.5          0.08915   
183       11.410         14.92           73.53      402.0          0.09059   
194       14.860         23.21          100.40      671.4          0.10440   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
462           0.05223         0.03476              0.01737         0.1707   
146           0.17000         0.16590              0.07415         0.2678   
445           0.09218         0.05441              0.04274         0.1820   
234           0.04087         0.01652              0.01667         0.1551   
516           0.12480         0.15690              0.09451         0.1860   
..                ...             ...                  ...            ...   
371           0.06934         0.03393              0.02657         0.1721   
95            0.13130         0.14650              0.08683         0.2095   
440           0.11130         0.09457              0.03613         0.1489   
183           0.08155         0.06181              0.02361         0.1167   
194           0.19800         0.16970              0.08878         0.1737   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
462                 0.05433  ...         15.40          31.98   
146                 0.07371  ...         13.74          26.38   
445                 0.06850  ...         12.98          30.36   
234                 0.06403  ...         10.51          19.16   
516                 0.05941  ...         21.86          26.20   
..                      ...  ...           ...            ...   
371                 0.05544  ...         16.20          15.73   
95                  0.05649  ...         24.22          31.59   
440                 0.06640  ...         12.36          26.87   
183                 0.06217  ...         12.37          17.70   
194                 0.06672  ...         16.08          27.78   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
462           100.40       734.6            0.1017            0.14600   
146            91.93       591.7            0.1385            0.40920   
445            84.48       513.9            0.1311            0.18220   
234            65.74       335.9            0.1504            0.09515   
516           142.20      1493.0            0.1492            0.25360   
..               ...         ...               ...                ...   
371           104.50       819.1            0.1126            0.17370   
95            156.10      1750.0            0.1190            0.35390   
440            90.14       476.4            0.1391            0.40820   
183            79.12       467.2            0.1121            0.16100   
194           118.60       784.7            0.1316            0.46480   

     concavity_worst  concave points_worst  symmetry_worst  \
462          0.14720               0.05563          0.2345   
146          0.45040               0.18650          0.5774   
445          0.16090               0.12020          0.2599   
234          0.07161               0.07222          0.2757   
516          0.37590               0.15100          0.3074   
..               ...                   ...             ...   
371          0.13620               0.08178         

In [6]:
print(type(xtrain),type(ytrain))
print(xtrain.shape)
print(ytrain.shape)

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
(455, 30)
(455,)


In [7]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.fit_transform(xtest)

In [8]:
encoder = LabelEncoder()
ytrain = encoder.fit_transform(ytrain)
ytest = encoder.fit_transform(ytest)


In [9]:
xtrain_tensor = torch.from_numpy(xtrain)
xtest_tensor = torch.from_numpy(xtest)
ytrain_tensor = torch.from_numpy(ytrain)
ytest_tensor = torch.from_numpy(ytest)

print(type(xtest_tensor),xtest_tensor.shape)
print(type(ytest_tensor),ytest_tensor.shape)

<class 'torch.Tensor'> torch.Size([114, 30])
<class 'torch.Tensor'> torch.Size([114])


In [10]:
class MySimpleNN():

    def __init__(self , x):

        self.weights = torch.rand(x.shape[1],1,dtype=torch.float64 , requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64 , requires_grad=True)  
        # x.shape[0],1 ==> 1
        # (200,1) + (1,) → PyTorch automatically expands bias to (200,1)

    def forward(self , x):

        z = torch.matmul( x , self.weights) + self.bias 
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y_target):

        epsilon = 1e-8
        y_pred = torch.clamp( y_pred , min = epsilon,max = 1 - epsilon)

        loss = -( y_target*torch.log(y_pred) + (1-y_target)*torch.log(1-y_pred) ).mean()

        return loss


In [11]:
learning_rate = 0.1
epochs = 25

model = MySimpleNN(xtrain_tensor)

print(type(model.weights) , model.weights.shape)
print(model.weights)

print(type(model.bias),model.bias.shape)


<class 'torch.Tensor'> torch.Size([30, 1])
tensor([[0.5449],
        [0.6049],
        [0.2700],
        [0.1131],
        [0.4808],
        [0.0185],
        [0.9580],
        [0.5160],
        [0.0071],
        [0.9736],
        [0.2734],
        [0.9043],
        [0.8476],
        [0.1004],
        [0.7017],
        [0.1334],
        [0.3150],
        [0.8644],
        [0.0550],
        [0.6900],
        [0.6522],
        [0.4910],
        [0.6012],
        [0.4037],
        [0.2926],
        [0.9467],
        [0.0599],
        [0.5105],
        [0.9837],
        [0.7301]], dtype=torch.float64, requires_grad=True)
<class 'torch.Tensor'> torch.Size([1])


In [13]:
# # Training Pipeline

for epoch in range(epochs):
    
    # Forward pass
    y_pred = model.forward(xtrain_tensor)

    # Calculating Loss
    loss = model.loss_function(y_pred,ytrain_tensor)

    # Backward Pass
    loss.backward()

    # # model parameters upgrade
    with torch.no_grad():
       
        model.weights -= learning_rate * (model.weights.grad)
        model.bias -= learning_rate * (model.bias.grad)

    # zero gradients   (better to do before loss.backward())
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')
    # loss in form of 0 dim vector , thats why we use loss.item()


Epoch: 1, Loss: 3.6637988830914625
Epoch: 2, Loss: 3.510141031775913
Epoch: 3, Loss: 3.3560177093945995
Epoch: 4, Loss: 3.1994462351831836
Epoch: 5, Loss: 3.0364160859421725
Epoch: 6, Loss: 2.8680734685139884
Epoch: 7, Loss: 2.6947579752809308
Epoch: 8, Loss: 2.5228446261560493
Epoch: 9, Loss: 2.3487704561246026
Epoch: 10, Loss: 2.173326707303485
Epoch: 11, Loss: 1.9981877103375352
Epoch: 12, Loss: 1.831144896899959
Epoch: 13, Loss: 1.673719357355623
Epoch: 14, Loss: 1.5275201847694038
Epoch: 15, Loss: 1.3941662285906784
Epoch: 16, Loss: 1.2751815212568973
Epoch: 17, Loss: 1.1718111593023202
Epoch: 18, Loss: 1.0846814923920227
Epoch: 19, Loss: 1.0133910393266656
Epoch: 20, Loss: 0.9564462134294432
Epoch: 21, Loss: 0.9116762532647746
Epoch: 22, Loss: 0.8767051762436141
Epoch: 23, Loss: 0.8492893483843733
Epoch: 24, Loss: 0.8275396142379783
Epoch: 25, Loss: 0.8099989930472209


In [14]:
print(model.weights)
print(model.bias)

tensor([[ 0.2128],
        [ 0.2216],
        [-0.0948],
        [-0.2285],
        [ 0.0214],
        [-0.6095],
        [ 0.3330],
        [-0.0744],
        [-0.4049],
        [ 0.5498],
        [-0.1671],
        [ 0.6043],
        [ 0.4003],
        [-0.2782],
        [ 0.3864],
        [-0.4014],
        [-0.1212],
        [ 0.3291],
        [-0.1786],
        [ 0.2410],
        [ 0.2624],
        [ 0.0781],
        [ 0.1821],
        [ 0.0135],
        [-0.1725],
        [ 0.3827],
        [-0.5160],
        [-0.0744],
        [ 0.6407],
        [ 0.2154]], dtype=torch.float64, requires_grad=True)
tensor([-0.1549], dtype=torch.float64, requires_grad=True)


In [15]:
# model evaluation
with torch.no_grad():

  y_pred = model.forward(xtest_tensor)
  y_pred = (y_pred > 0.5).float()  # threshold
  accuracy = (y_pred == ytest_tensor).float().mean()

print("Accuracy" , accuracy.item())

Accuracy 0.5166205167770386


In [16]:
# Note : 
# 1. PyTorch builds a computation graph during forward pass
# 2. Then loss.backward() uses that graph to compute gradients