In [1]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
print(df.shape)
print(df.columns)
df.drop(columns=['id' ,'Unnamed: 32' ] , inplace = True)

df.head()

(569, 33)
Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [4]:
xtrain,xtest,ytrain,ytest = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [5]:
xtrain

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
37        13.030         18.42           82.61      523.8          0.08983   
270       14.290         16.82           90.30      632.6          0.06429   
472       14.920         14.93           96.45      686.9          0.08098   
390       10.260         12.22           65.75      321.6          0.09996   
400       17.910         21.02          124.40      994.0          0.12300   
..           ...           ...             ...        ...              ...   
85        18.460         18.52          121.10     1075.0          0.09874   
157       16.840         19.46          108.40      880.2          0.07445   
6         18.250         19.98          119.60     1040.0          0.09463   
286       11.940         20.76           77.87      441.0          0.08605   
103        9.876         19.40           63.95      298.3          0.10050   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
37            0.03766         0.02562              0.02923         0.1467   
270           0.02675         0.00725              0.00625         0.1508   
472           0.08549         0.05539              0.03221         0.1687   
390           0.07542         0.01923              0.01968         0.1800   
400           0.25760         0.31890              0.11980         0.2113   
..                ...             ...                  ...            ...   
85            0.10530         0.13350              0.08795         0.2132   
157           0.07223         0.05150              0.02771         0.1844   
6             0.10900         0.11270              0.07400         0.1794   
286           0.10110         0.06574              0.03791         0.1588   
103           0.09697         0.06154              0.03029         0.1945   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
37                  0.05863  ...         13.30          22.81   
270                 0.05376  ...         14.91          20.65   
472                 0.05669  ...         17.18          18.22   
390                 0.06569  ...         11.38          15.65   
400                 0.07115  ...         20.80          27.78   
..                      ...  ...           ...            ...   
85                  0.06022  ...         22.93          27.68   
157                 0.05268  ...         18.22          28.07   
6                   0.05742  ...         22.88          27.66   
286                 0.06766  ...         13.24          27.29   
103                 0.06322  ...         10.76          26.83   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
37             84.46       545.9           0.09701            0.04619   
270            94.44       684.6           0.08567            0.05036   
472           112.00       906.6           0.10650            0.27910   
390            73.23       394.5           0.13430            0.16500   
400           149.60      1304.0           0.18730            0.59170   
..               ...         ...               ...                ...   
85            152.20      1603.0           0.13980            0.20890   
157           120.30      1032.0           0.08774            0.17100   
6             153.20      1606.0           0.14420            0.25760   
286            92.20       546.1           0.11160            0.28130   
103            72.22       361.2           0.15590            0.23020   

     concavity_worst  concave points_worst  symmetry_worst  \
37           0.04833               0.05013          0.1987   
270          0.03866               0.03333          0.2458   
472          0.31510               0.11470          0.2688   
390          0.08615               0.06696          0.2937   
400          0.90340               0.19640          0.3245   
..               ...                   ...             ...   
85           0.31570               0.16420         

In [6]:
print(type(xtrain),type(ytrain))
print(xtrain.shape)
print(ytrain.shape)

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
(455, 30)
(455,)


In [7]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.fit_transform(xtest)

In [8]:
encoder = LabelEncoder()
ytrain = encoder.fit_transform(ytrain)
ytest = encoder.fit_transform(ytest)


In [9]:
xtrain_tensor = torch.from_numpy(xtrain)
xtest_tensor = torch.from_numpy(xtest)
ytrain_tensor = torch.from_numpy(ytrain)
ytest_tensor = torch.from_numpy(ytest)

print(type(xtest_tensor),xtest_tensor.shape)
print(type(ytest_tensor),ytest_tensor.shape)

<class 'torch.Tensor'> torch.Size([114, 30])
<class 'torch.Tensor'> torch.Size([114])


In [10]:
class MySimpleNN():

    def __init__(self , x):

        self.weights = torch.rand(x.shape[1],1,dtype=torch.float64 , requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64 , requires_grad=True)  
        # x.shape[0],1 ==> 1
        # (200,1) + (1,) → PyTorch automatically expands bias to (200,1)

    def forward(self , x):

        z = torch.matmul( x , self.weights) + self.bias 
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y_target):

        epsilon = 1e-8
        y_pred = torch.clamp( y_pred , min = epsilon,max = 1 - epsilon)

        loss = -( y_target*torch.log(y_pred) + (1-y_target)*torch.log(1-y_pred) ).mean()

        return loss


In [11]:
learning_rate = 0.1
epochs = 25

model = MySimpleNN(xtrain_tensor)

print(type(model.weights) , model.weights.shape)
print(model.weights)

print(type(model.bias),model.bias.shape)


<class 'torch.Tensor'> torch.Size([30, 1])
tensor([[0.6866],
        [0.7404],
        [0.4655],
        [0.4880],
        [0.0946],
        [0.9155],
        [0.6426],
        [0.5485],
        [0.2919],
        [0.6974],
        [0.5180],
        [0.3988],
        [0.0485],
        [0.4693],
        [0.8084],
        [0.5788],
        [0.1616],
        [0.9751],
        [0.1296],
        [0.8379],
        [0.4348],
        [0.8322],
        [0.6557],
        [0.0903],
        [0.2623],
        [0.7996],
        [0.4085],
        [0.8981],
        [0.9171],
        [0.6203]], dtype=torch.float64, requires_grad=True)
<class 'torch.Tensor'> torch.Size([1])


In [12]:
# # Training Pipeline

for epoch in range(epochs):
    
    # Forward pass
    y_pred = model.forward(xtrain_tensor)

    # Calculating Loss
    loss = model.loss_function(y_pred,ytrain_tensor)

    # Backward Pass
    loss.backward()

    # # model parameters upgrade
    with torch.no_grad():
       
        model.weights -= learning_rate * (model.weights.grad)
        model.bias -= learning_rate * (model.bias.grad)

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 4.043237483572593
Epoch: 2, Loss: 3.9099530165819836
Epoch: 3, Loss: 3.772909302080983
Epoch: 4, Loss: 3.6258601303516227
Epoch: 5, Loss: 3.475132456978251
Epoch: 6, Loss: 3.323547834477546
Epoch: 7, Loss: 3.1713507859900956
Epoch: 8, Loss: 3.0209944567857803
Epoch: 9, Loss: 2.869294729911984
Epoch: 10, Loss: 2.712783377488086
Epoch: 11, Loss: 2.5490645732464823
Epoch: 12, Loss: 2.3768364619547557
Epoch: 13, Loss: 2.2048023206540064
Epoch: 14, Loss: 2.032977012812246
Epoch: 15, Loss: 1.866668509294346
Epoch: 16, Loss: 1.709475861850125
Epoch: 17, Loss: 1.5630287499559137
Epoch: 18, Loss: 1.42916590666366
Epoch: 19, Loss: 1.3096581115138777
Epoch: 20, Loss: 1.205628830779267
Epoch: 21, Loss: 1.1172147839029327
Epoch: 22, Loss: 1.0437198611614946
Epoch: 23, Loss: 0.9837293117028
Epoch: 24, Loss: 0.9353037851867728
Epoch: 25, Loss: 0.8963756308407114


In [13]:
print(model.weights)
print(model.bias)

tensor([[ 0.2403],
        [ 0.3175],
        [-0.0110],
        [ 0.0472],
        [-0.3407],
        [ 0.2220],
        [-0.0511],
        [-0.1218],
        [-0.1488],
        [ 0.3205],
        [ 0.0810],
        [ 0.1822],
        [-0.4005],
        [ 0.0911],
        [ 0.5819],
        [-0.0134],
        [-0.3126],
        [ 0.3795],
        [-0.0492],
        [ 0.3691],
        [-0.0548],
        [ 0.3916],
        [ 0.1389],
        [-0.3791],
        [-0.1909],
        [ 0.1555],
        [-0.2481],
        [ 0.2121],
        [ 0.5360],
        [ 0.0828]], dtype=torch.float64, requires_grad=True)
tensor([-0.1315], dtype=torch.float64, requires_grad=True)


In [18]:
# model evaluation
with torch.no_grad():

  y_pred = model.forward(xtest_tensor)
  y_pred = (y_pred > 0.5).float()  # threshold
  accuracy = (y_pred == ytest_tensor).float().mean()

print("Accuracy" , accuracy.item())

Accuracy 0.5156971216201782
