In [80]:
import torch
import torch.nn as nn


class Model(nn.Module):

    def __init__(self , num_features):

        super().__init__()

        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self , features):
        
        
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [81]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features) # ==>model.forward(features) , not work if diff function name


tensor([[0.3882],
        [0.4705],
        [0.4417],
        [0.4559],
        [0.4047],
        [0.4665],
        [0.4022],
        [0.4252],
        [0.4478],
        [0.4227]], grad_fn=<SigmoidBackward0>)

In [82]:
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.0748, -0.1809, -0.1309, -0.2888, -0.1731]], requires_grad=True)
Parameter containing:
tensor([0.1619], requires_grad=True)


In [83]:
from torchinfo import summary

summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [84]:
class Model(nn.Module):

    def __init__(self , num_features):

        super().__init__()

        self.linear = nn.Linear(num_features , 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self , features):
        
        
        out = self.linear(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [85]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features) # ==>model.forward(features) , not work if diff function name

summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [86]:
class Model(nn.Module):

    def __init__(self , num_features):

        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features , 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self , features):
        
        out = self.network(features)

        return out

In [87]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features) # ==>model.forward(features) , not work if diff function name

summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [88]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [89]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [90]:
print(df.shape)
print(df.columns)
df.drop(columns=['id' ,'Unnamed: 32' ] , inplace = True)

df.head()

(569, 33)
Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [91]:
xtrain,xtest,ytrain,ytest = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [92]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.fit_transform(xtest)

In [93]:
encoder = LabelEncoder()
ytrain = encoder.fit_transform(ytrain)
ytest = encoder.fit_transform(ytest)


In [94]:
xtrain_tensor = torch.from_numpy(xtrain).float()
xtest_tensor = torch.from_numpy(xtest).float()
ytrain_tensor = torch.from_numpy(ytrain).float()
ytest_tensor = torch.from_numpy(ytest).float()

print(type(xtest_tensor),xtest_tensor.shape)
print(type(ytest_tensor),ytest_tensor.shape)

<class 'torch.Tensor'> torch.Size([114, 30])
<class 'torch.Tensor'> torch.Size([114])


In [95]:

class MySimpleNN(nn.Module):

    def __init__(self , num_features):

        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features , 1),
            nn.Sigmoid()
        )
        
    def forward(self , features):
        
        out = self.network(features)
        return out
    
    def loss_function(self,y_pred,y_target):

        epsilon = 1e-8
        y_pred = torch.clamp( y_pred , min = epsilon,max = 1 - epsilon)

        loss = -( y_target*torch.log(y_pred) + (1-y_target)*torch.log(1-y_pred) ).mean()

        return loss



In [106]:
model = MySimpleNN(xtrain_tensor.shape[1])

learning_rate = 0.1
epochs = 25

summary(model , input_size = xtrain_tensor.shape)

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 1]                  31
│    └─Sigmoid: 2-2                      [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06

In [97]:
y_pred = model.forward(xtrain_tensor)
print(y_pred.shape , ytrain_tensor.shape)

torch.Size([455, 1]) torch.Size([455])


In [101]:
print(ytrain_tensor.shape)
print(ytrain_tensor.unsqueeze(1).shape)

torch.Size([455])
torch.Size([455, 1])


In [105]:
print(model.network)
print(model.network[0].weight)



Sequential(
  (0): Linear(in_features=30, out_features=1, bias=True)
  (1): Sigmoid()
)
Parameter containing:
tensor([[ 0.1278,  0.1688,  0.0338,  0.1796, -0.0209,  0.1578, -0.0760,  0.0821,
          0.0436, -0.1459,  0.1329,  0.0724, -0.0585, -0.0628, -0.0716, -0.1502,
         -0.0136,  0.0831, -0.1519, -0.1181,  0.0948,  0.1721,  0.0024,  0.1557,
          0.1759, -0.1487,  0.1398, -0.0054, -0.1736, -0.1018]],
       requires_grad=True)


In [115]:
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),learning_rate)

for epoch in range(epochs):

    # Forward 
    y_pred = model.forward(xtrain_tensor)
    
    # Loss calculation
    # loss = model.loss_function(y_pred , ytrain_tensor) in this pytorch auto broadcast
    loss = loss_function(y_pred , ytrain_tensor.unsqueeze(1))

    # Zero gradient
    # model.network[0].weight.grad.zero_()   (these grads are created after loss.backward())
    # model.network[0].bias.grad.zero_()
    optimizer.zero_grad()  # do zero if not None , if None then keep them None

    loss.backward()

    # Parameter upgrade
    # with torch.no_grad():
    #     model.network[0].weight -= learning_rate * model.network[0].weight.grad
    #     model.network[0].bias -= learning_rate * model.network[0].bias.grad
    optimizer.step()


    print(f'Epoch: {epoch + 1}, Loss: {loss.item()} ')

Epoch: 1, Loss: 0.10082059353590012 
Epoch: 2, Loss: 0.10054911673069 
Epoch: 3, Loss: 0.1002812385559082 
Epoch: 4, Loss: 0.10001687705516815 
Epoch: 5, Loss: 0.09975598752498627 
Epoch: 6, Loss: 0.09949847310781479 
Epoch: 7, Loss: 0.09924428164958954 
Epoch: 8, Loss: 0.09899330884218216 
Epoch: 9, Loss: 0.09874550998210907 
Epoch: 10, Loss: 0.0985008254647255 
Epoch: 11, Loss: 0.09825918823480606 
Epoch: 12, Loss: 0.0980205312371254 
Epoch: 13, Loss: 0.09778480976819992 
Epoch: 14, Loss: 0.09755192697048187 
Epoch: 15, Loss: 0.09732187539339066 
Epoch: 16, Loss: 0.0970945730805397 
Epoch: 17, Loss: 0.09686996787786484 
Epoch: 18, Loss: 0.09664802253246307 
Epoch: 19, Loss: 0.09642866253852844 
Epoch: 20, Loss: 0.09621184319257736 
Epoch: 21, Loss: 0.09599753469228745 
Epoch: 22, Loss: 0.09578569233417511 
Epoch: 23, Loss: 0.09557623416185379 
Epoch: 24, Loss: 0.09536916762590408 
Epoch: 25, Loss: 0.09516438841819763 
